version: '3.8'            # Version 3.8 is quite new and should work

services:
  app:
    image: bloglist-frontend-dev
    build:
      context: . # The context will pick this directory as the "build context"
      dockerfile: dev.Dockerfile # This will simply tell which dockerfile to read
    volumes:
      - ./:/usr/src/app # The path can be relative, so ./ is enough to say "the same location as the docker-compose.dev.yml"
    ports:
      - 3000:3000
    environment:
      - REACT_APP_BACKEND_URL=//localhost:3003
    container_name: bloglist-frontend-dev
